### ISSUE TITLE
Rsyslog errors and start failure

### ISSUE THREAD

**Issue by Fmstrat** [tozd/docker-postfix#1]
Fresh setup won't start:

Started with:
```
root@li1749-39:/data/docker/containers# mkdir -p ./postfix/data/logs/
root@li1749-39:/data/docker/containers# mkdir -p ./postfix/data/spool/
```

Then my docker-compose.yml:
```
  postfix:
    image: tozd/postfix
    container_name: postfix
    hostname: linode
    domainname: DOMAIN.com
    networks:
      - intnet
    ports:
      - "33025:25"
      - "33587:587"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./postfix/data/logs/:/var/log/postfix/
      - ./postfix/data/spool/:/var/spool/postfix/
    environment:
      - MAILNAME='linode.DOMAIN.com'
      - MY_NETWORKS='172.18.0.0/16 127.0.0.0/8'
      - ROOT_ALIAS='USER@DOMAIN.com'
      - MY_DESTINATION='localhost.localdomain, localhost'
```

Then the execution:
```
root@li1749-39:/data/docker/containers# docker-compose up postfix
Starting postfix
Attaching to postfix
postfix                | rsyslogd: error: option -c is no longer supported - ignored
postfix                | rsyslogd: cannot create '/var/spool/postfix/dev/log': No such file or directory
postfix                | rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
postfix                | rsyslogd: activation of module imklog failed [try http://www.rsyslog.com/e/2145 ]
postfix                | rsyslogd: Could no open output pipe '/dev/xconsole': No such file or directory [try http://www.rsyslog.com/e/2039 ]
```

I then tried:
```
root@li1749-39:/data/docker/containers# mkdir -p ./postfix/data/spool/dev
root@li1749-39:/data/docker/containers# docker-compose up postfix
Starting postfix
Attaching to postfix
postfix                | rsyslogd: error: option -c is no longer supported - ignored
postfix                | rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
postfix                | rsyslogd: activation of module imklog failed [try http://www.rsyslog.com/e/2145 ]
postfix                | rsyslogd: Could no open output pipe '/dev/xconsole': No such file or directory [try http://www.rsyslog.com/e/2039 ]
```

Only removed one of the errors.
